[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'cache_forge'
solc_version = "0.8.24"
evm_version = 'paris'
via-ir = true
optimizer = true
optimizer_runs = 1000


# no_match_test = "testPerformLotteryAndClaim"

 remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "openzeppelin-contracts/=node_modules/@openzeppelin/",
    "erc6551/=lib/tokenbound/lib/erc6551/src",        
    "murky/=lib/murky/",
    "@tokenbound/contracts/=node_modules/@tokenbound/contracts/",
    "@tokenbound/sdk/=node_modules/@tokenbound/sdk/"
 ]
