[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'cache_forge'
solc_version = "0.8.20"
evm_version = 'paris'
via-ir = true
optimizer = true
optimizer_runs = 1000


no_match_test = "testPerformLotteryAndClaim"

# remappings = [
#     # "lib/tokenbound:@openzeppelin/=node_modules/@openzeppelin/",
#     "@openzeppelin/=node_modules/@openzeppelin/",
#     "openzeppelin-contracts/=node_modules/@openzeppelin/",
#     # "erc6551/=node_modules/@openzeppelin/contracts/",
# ]
