name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  PRIVATE_KEY: '${{ secrets.PRIVATE_KEY }}'
  MUMBAI_RPC: '${{ secrets.MUMBAI_RPC }}'
  THIRDWEB_API_KEY: '${{ secrets.THIRDWEB_API_KEY }}'
  ETHERSCAN_API_KEY: '${{ secrets.ETHERSCAN_API_KEY }}'
  POLYGONSCAN_API_KEY: '${{ secrets.POLYGONSCAN_API_KEY }}'
  CHAIN: '${{ secrets.CHAIN }}'
jobs:
  start-hardhat-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - run: npm install
      - run: forge install foundry-rs/forge-std --no-commit
      - run: npm test