name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  PRIVATE_KEY: "${{ secrets.PRIVATE_KEY }}"
  MUMBAI_RPC: "${{ secrets.MUMBAI_RPC }}"
  THIRDWEB_API_KEY: "${{ secrets.THIRDWEB_API_KEY }}"
  ETHERSCAN_API_KEY: "${{ secrets.ETHERSCAN_API_KEY }}"
  POLYGONSCAN_API_KEY: "${{ secrets.POLYGONSCAN_API_KEY }}"
  CHAIN: "${{ secrets.CHAIN }}"
jobs:
  start-hardhat-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - run: git submodule update
      - run: npm install
      - run: npm test
      - name: Run snapshot
        run: forge snapshot
